/* ==========================================================================
   PIONEER DASHBOARD -- PDF EXPORT MODULE
   Uses jsPDF (window.jspdf.jsPDF) -- no autotable, manual layout.
   ========================================================================== */

window.PioneerExport = (function () {
  var TEAL  = [42, 157, 143];
  var INK   = [27, 42, 44];
  var MUTED = [138, 147, 150];
  var GOLD  = [233, 196, 106];

  function todayISO() {
    var d = new Date();
    return d.toISOString().slice(0, 10);
  }

  // Manual watermark: large rotated grey text per page.
  function addWatermark(doc) {
    var w = doc.internal.pageSize.getWidth();
    var h = doc.internal.pageSize.getHeight();
    doc.saveGraphicsState();
    doc.setGState(new doc.GState({ opacity: 0.08 }));
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(64);
    doc.text('DEMO DATA', w / 2, h / 2, { angle: -30, align: 'center', baseline: 'middle' });
    doc.restoreGraphicsState();
  }

  function addHeader(doc, title, subtitle) {
    var w = doc.internal.pageSize.getWidth();
    doc.setFillColor.apply(doc, TEAL);
    doc.rect(0, 0, w, 14, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(title, 12, 9.5);
    if (subtitle) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text(subtitle, w - 12, 9.5, { align: 'right' });
    }
  }

  function addFooter(doc, pageNumber) {
    var w = doc.internal.pageSize.getWidth();
    var h = doc.internal.pageSize.getHeight();
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor.apply(doc, MUTED);
    doc.text(
      'Generated by Pioneer Dashboard -- verify all data independently before making decisions.',
      12, h - 6
    );
    doc.text('Page ' + pageNumber, w - 12, h - 6, { align: 'right' });
  }

  function sectionTitle(doc, x, y, text) {
    doc.setFillColor.apply(doc, TEAL);
    doc.rect(x, y - 4, 2, 6, 'F');
    doc.setTextColor.apply(doc, TEAL);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(text, x + 5, y);
  }

  function fieldLine(doc, x, y, label, value, confidenceLow) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor.apply(doc, MUTED);
    doc.text(label.toUpperCase(), x, y);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    doc.setTextColor.apply(doc, INK);

    var valueText = (value === null || value === undefined || value === '') ? 'No data available' : String(value);
    var maxWidth = doc.internal.pageSize.getWidth() - x - 14;
    var lines = doc.splitTextToSize(valueText, maxWidth);
    doc.text(lines, x, y + 5);

    if (confidenceLow) {
      doc.setFillColor.apply(doc, GOLD);
      doc.circle(x + doc.getTextWidth(label.toUpperCase()) + 4, y - 1, 1.8, 'F');
    }

    return y + 5 + (lines.length - 1) * 5 + 7;
  }

  function pageBreakIfNeeded(doc, y, pageState) {
    var h = doc.internal.pageSize.getHeight();
    if (y > h - 20) {
      addFooter(doc, pageState.page);
      doc.addPage();
      pageState.page++;
      addWatermark(doc);
      addHeader(doc, pageState.title, pageState.subtitle);
      return 24;
    }
    return y;
  }

  // ---------- Country export ----------
  function exportCountry(country, sections, visibleByField, fieldsSpec) {
    var jsPDF = window.jspdf.jsPDF;
    var doc = new jsPDF({ unit: 'mm', format: 'a4' });
    var pageState = {
      page: 1,
      title: 'Pioneer Research Report -- ' + country.name,
      subtitle: todayISO()
    };

    addWatermark(doc);
    addHeader(doc, pageState.title, pageState.subtitle);

    var y = 22;
    doc.setTextColor.apply(doc, INK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text(country.flag + '  ' + country.name, 12, y + 6);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor.apply(doc, MUTED);
    doc.text(country.region + '  |  Capital: ' + country.capital, 12, y + 12);
    y += 22;

    sections.forEach(function (sectionKey) {
      var spec = fieldsSpec[sectionKey];
      var sectionData = country[sectionKey];
      var sectionConf = country.confidence[sectionKey] || {};

      var anyVisible = Object.keys(spec).some(function (key) {
        return visibleByField[sectionKey + '.' + key] !== false;
      });
      if (!anyVisible) return;

      y = pageBreakIfNeeded(doc, y + 4, pageState);
      sectionTitle(doc, 12, y, spec.__label || sectionKey.toUpperCase());
      y += 6;

      Object.keys(spec).forEach(function (key) {
        if (key.startsWith('__')) return;
        if (visibleByField[sectionKey + '.' + key] === false) return;
        var value = sectionData ? sectionData[key] : null;
        var displayValue = formatValueForPdf(key, value);
        var conf = sectionConf[key] === 'low';
        y = pageBreakIfNeeded(doc, y, pageState);
        y = fieldLine(doc, 14, y, spec[key].label, displayValue, conf);
      });

      y += 4;
    });

    addFooter(doc, pageState.page);
    doc.save(country.id + '-pioneer-report.pdf');
  }

  // ---------- Comparison export ----------
  function exportComparison(countries, sections, visibleByField, fieldsSpec) {
    var jsPDF = window.jspdf.jsPDF;
    var doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
    var pageState = {
      page: 1,
      title: 'Pioneer Comparison Report',
      subtitle: todayISO()
    };

    addWatermark(doc);
    addHeader(doc, pageState.title, pageState.subtitle);

    var y = 22;
    doc.setTextColor.apply(doc, INK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    var names = countries.map(function (c) { return c.flag + ' ' + c.name; }).join('   vs   ');
    doc.text(names, 12, y + 4);
    y += 14;

    var pageW = doc.internal.pageSize.getWidth();
    var labelCol = 60;
    var colW = (pageW - labelCol - 16) / countries.length;

    // Header row
    function drawHeader() {
      doc.setFillColor.apply(doc, TEAL);
      doc.rect(12, y - 5, pageW - 24, 7, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('FIELD', 14, y);
      countries.forEach(function (c, i) {
        doc.text(c.flag + ' ' + c.name, 12 + labelCol + i * colW + 2, y);
      });
      y += 6;
    }
    drawHeader();

    sections.forEach(function (sectionKey) {
      var spec = fieldsSpec[sectionKey];

      var anyVisible = Object.keys(spec).some(function (key) {
        return !key.startsWith('__') && visibleByField[sectionKey + '.' + key] !== false;
      });
      if (!anyVisible) return;

      y = pageBreakIfNeeded(doc, y + 2, pageState);
      if (y === 24) { drawHeader(); }

      doc.setFillColor(230, 242, 240);
      doc.rect(12, y - 4, pageW - 24, 5, 'F');
      doc.setTextColor.apply(doc, TEAL);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text((spec.__label || sectionKey).toUpperCase(), 14, y);
      y += 5;

      Object.keys(spec).forEach(function (key) {
        if (key.startsWith('__')) return;
        if (visibleByField[sectionKey + '.' + key] === false) return;

        y = pageBreakIfNeeded(doc, y, pageState);
        if (y === 24) { drawHeader(); }

        doc.setTextColor.apply(doc, INK);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        var labelLines = doc.splitTextToSize(spec[key].label, labelCol - 4);
        doc.text(labelLines, 14, y);

        countries.forEach(function (c, i) {
          var val = c[sectionKey] ? c[sectionKey][key] : null;
          var display = formatValueForPdf(key, val);
          var lines = doc.splitTextToSize(display, colW - 4);
          doc.text(lines, 12 + labelCol + i * colW + 2, y);
        });
        var maxLines = countries.reduce(function (m, c) {
          var val = c[sectionKey] ? c[sectionKey][key] : null;
          var d = formatValueForPdf(key, val);
          return Math.max(m, doc.splitTextToSize(d, colW - 4).length);
        }, labelLines.length);
        y += maxLines * 4 + 2;
        doc.setDrawColor(225, 227, 224);
        doc.line(12, y - 1, pageW - 12, y - 1);
      });
    });

    addFooter(doc, pageState.page);
    doc.save('pioneer-comparison-report.pdf');
  }

  function formatValueForPdf(key, value) {
    if (value === null || value === undefined || value === '') return 'No data available';
    if (Array.isArray(value)) return value.join(', ');
    if (typeof value === 'boolean') return value ? 'Yes' : 'No';
    if (key === 'historicalRates') return 'See app';
    if (typeof value === 'number' && /rent|grocery|salary|utilities|internet|meal|transport|cost/i.test(key)) {
      return 'A$' + value.toLocaleString();
    }
    return String(value);
  }

  return {
    exportCountry: exportCountry,
    exportComparison: exportComparison
  };
})();
